GET https://pokeapi.co/api/v2/pokemon

###

GET https://pokeapi.co/api/v2/pokemon/5

###

POST http://localhost:1337/api/pokemons/
Content-Type: application/json

{
  "data":{
    "name": "charmeleon",
    "type1": "fire",
    "type2": "",
    "cries": "https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/5.ogg",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
    "hp": 58
    }
}

###

PUT http://localhost:1337/api/pokemons/lud1vc9kgvylzfry4zaqqw1s
Content-Type: application/json

{

}

###
DELETE http://localhost:1337/api/pokemons/o1hy0bf8dcm7gkm0j1zpyc02
