GET https://pokeapi.co/api/v2/pokemon

###

GET https://pokeapi.co/api/v2/pokemon/

###

POST http://localhost:1337/api/pokemons/
Content-Type: application/json

{
  "data":{
    "name": "ivysaur",
    "type1": "grass",
    "type2": "poison",
    "cries": "",
    "sprite": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    "hp": 45
    }
}

###

PUT http://localhost:1337/api/pokemons/lud1vc9kgvylzfry4zaqqw1s
Content-Type: application/json

{

}

###
DELETE http://localhost:1337/api/pokemons/o1hy0bf8dcm7gkm0j1zpyc02
